version: "3"

services:

{{#boundedContexts}}
  generate-{{name}}:
    tty: true
    stdin_open: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    image: ghcr.io/jinyoung/gpt-engineer:v5
    command: ["-i"]
    volumes:
      - ../{{name}}:/project
{{/boundedContexts}}